spring.application.name=FoodRedistributionProject

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/FoodRedistributionAndReuse?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
server.servlet.context-path=/food
spring.datasource.username=root
spring.datasource.password=Aparna@04
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#jwt.secret means a secret key used to sign the token
jwt.secret=FoodRedistributionProjectSecretKey12345678901234567890
#this is token validation time=24 hr
jwt.expiration=86400000
#default server port 8080
#server.port=9090

#Aparna bearer token -"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFybmFAZ21haWwuY29tIiwiaWF0IjoxNzg0ODIxNjM3LCJleHAiOjE3ODQ5MDgwMzd9.QeOGI84ECQ7RL8CwKNtxM8jQiBwBBIIc9tzZj0JEgck"



